---
name: CatalystX-Example-YUIUploader
version: 0.01
author:
  - Robert Krimen
abstract: A YUI Uploader example for Catalyst
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Catalyst::Action::RenderView: 0
  Catalyst::Plugin::ConfigLoader: 0
  Catalyst::Plugin::Static::Simple: 0
  Catalyst::Runtime: 5.7012
  Catalyst::View::JSON: 0
  Catalyst::View::TT: 0
  Data::UUID: 0
  MIME::Types: 0
  YAML: 0
provides:
  CatalystX::Example::YUIUploader:
    file: lib/CatalystX/Example/YUIUploader.pm
    version: 0.01
  CatalystX::Example::YUIUploader::Controller::Root:
    file: lib/CatalystX/Example/YUIUploader/Controller/Root.pm
  CatalystX::Example::YUIUploader::View::JSON:
    file: lib/CatalystX/Example/YUIUploader/View/JSON.pm
  CatalystX::Example::YUIUploader::View::TT:
    file: lib/CatalystX/Example/YUIUploader/View/TT.pm
generated_by: Module::Build version 0.2806
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
